/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rv.proyect1.controllers;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author rafael
 */
public class ZodiacoGriego implements ZodiacoInterface {
    ArrayList<SignoZodiaco> signos;

    public ZodiacoGriego() {
        String tipo = "griego";
        signos = new ArrayList(12);
        signos.add(0, new SignoZodiaco(tipo, "Acuario", "Los Acuario se encontraran en un momento en el cual su forma de actuar sera poco convencional y deberan esforzarse por cambiar y llevar a termino sus proyectos. Esperense a que el año 2014 sea para Vds. muy explosivo y tenso, hasta que se decidan a reafirmarse y ser consecuentes con sus actos. Pero en Julio se encontraran con alguien, que se aliara con Vds. y sera algo muy constructivo para su vida. Su trabajo va a ser duro como lo viene siendo desde Octubre 2012, pero si siguen perseverando conseguiran tener exito a largo plazo. En Junio 2013 entraron en un circulo de prosperidad y continuaran asi. Buenos trabajos, ascensos, proyectos exitosos… Los estudiantes conseguiran sacar un buen año, aunque a costa de un duro esfuerzo. Neptuno esta en su casa del dinero desde Febrero del 2012 y lo seguira estando muchos años mas. Lo que significa, que el dinero les llovera del cielo y les seguira yendo muy bien. Tienen una intuicion muy buena, para los negocios y para las inversiones. Van camino de ganar mucho dinero. A partir del 16 de Julio, Jupiter entrara en su casa VII del Amor, el matrimonio y la vida social. Vds. no tienen problemas amorosos. La felicidad sigue con Vds. por muchos años. En 2014 disfrutaran de buena salud, pero a partir del 16 de Julio dos planetas se alinearan y provocaran tensiones en este campo. Deberan cuidarse un poco. Un proyecto de una enorme envergadura aparecera a partir del 26 de Julio. Urano estara retrogrado y es algo que Vds. querran hacer para si mismos y que lo van a crear. Los temas que mas les van a interesar este año son: amor, relaciones de pareja, salud, finanzas, communication e intelectualidad, espiritualidad, carreras profesional. Sus logros mas importantes en 2014 estaran relacionados con: espiritualidad, religion, filosofia, estudios superiores, viajes al extranjero, trabajo, amor, relaciones de pareja."));
        signos.add(1, new SignoZodiaco(tipo, "Aries", "La clave para los Aries en 2014 sera como manejar sus relaciones tanto laborales como personales. Desea una mayor liberacion y explorar nuevos terrenos… Cosa que a finales de año conseguira de alguna forma, porque apareceran interesantes posibilidades. Hay posibilidad de recibir una agradable sorpresa financiera en Mayo este año asi que ¡¡Preparense para una alegria inesperada Aries!!. En 2014 los Aries seguiran con la misma tendencia que llevan viviendo desde 2011, cambios, imprevistos, oportunidades… Pero lo importante es que Aries ha aprendido a sentirse bien gracias a estos cambios, liberado de todo tipo de ataduras, para perseguir sus sueños. El profundo desarrollo espiritual, que estan viviendo comenzo en Febrero del 2012, cuando su casa XII de la Espiritualidad paso al signo de Piscis. Esto produjo estos cambios y esta evolucion interior, que durara todavia un año mas, pero que les estan situando en la posicion correcta para afrontar todo en la vida. Pluton continuara en Capricornio, en su casa X, por lo que su trayectoria profesional y los estudios seguiran en la misma direccion que los ultimos años. En definitiva, 2014 promete ser para Aries un año prospero y feliz, con mucha creatividad y suerte en las inversiones financieras. Buen momento para embarazarse, si lo desean. Sera muy importante su imagen, el sexo, las relaciones de pareja, el hogar, los placeres, la familia. Sus logros mas importantes en 2014 estaran relacionados con: el tema de la reencarnacion y del ocultismo, la familia, los hijos, la diversion, el sexo, la transformacion, la reencarnacion, la muerte, la vida despues de la muerte, el amor y las relaciones."));
        signos.add(2, new SignoZodiaco(tipo, "Capricornio ", "El año 2014 sera como un renacer para los Capricornio, con muchos de Vds. buscando nuevas oportunidades y nuevos trabajos, donde ver realizados sus objetivos laborales. Es necesario hacer mucha vida social, para poder relacionarse con gente, que le puede abrir las puertas a nuevas oportunidades. Necesita encontrar nuevos aliados. Ambiente mas relajado en Diciembre. 2014, al igual que 2013 fue el año del amor para los Capricornio. El amor y la amistad estan en el aire. Durante años han estado reinventandose y transformandose, para adaptarse a las nuevas tecnologias. Los amigos les han estado ayudando tambien, pero queda mucho trabajo por hacer. A partir del 16 de Julio todo ira mejor, incluso puede que tengan exito. La Economia ira cogeando como siempre, pero a partir del 16 de Julio podrian ir mejor. Su vida profesional sera activa, pero frenetica. Podria conseguir el exito a costa de duro trabajo y mucho esfuerzo. Lo dificil sera compaginar su trabajo con sus obligaciones familiares. Neptuno estara en su casa III, la de la Comunicacion, lo que significa que ha mejorado en su vida social, porque se ha esforzado en comportarse correctamente y no como le da la gana. Los estudiantes este año tendran que hacer el esfuerzo de aprender a integrar la logica y la intuicion. Su situacion familiar sera inestable y cambiante y les afectara mucho. Su reto en 2014 sera mantener su equilibrio emocional, muy debilitado ya. Sus areas de mayor interes seran: el amor, la seduccion, su cuerpo, su imagen sus placeres personales, la comunicacion, la intelectualidad, los impuestos, las deudas, las propiedades, el ocultismo, los amigos, las actividades, el sexo, la reinvencion personal. Sus logros mas importantes en 2014 estaran relacionados con: el sexo, el ligar, el amor, la pareja, los amigos, las actividades grupales, la reinvencion personal, las propiedades, los impuestos, el ocultismo y los estudios. "));
        signos.add(3, new SignoZodiaco(tipo, "Cancer" , "En el año 2014 haran grandes progresos en su vida laboral o en sus estudios. Los mejores meses para encontrar oportunidades y avanzar espectacularmente seran: Marzo, Abril, Septiembre, Octubre y Diciembre. Su economia mejorara considerablemente a partir del mes de Julio. Tras una dura etapa vivida desde 2011, el 2013 fue bastante mejor y en 2014 todo sera mas facil para los Cancer. Deberan controlar un poco la salud, pero todo ira bien. Despues de todo lo duro que les ha pasado, en 2014 entran en una etapa de prosperidad y es debido a que Jupiter entro en Junio 2013 en Cancer y todo ha cambiado. Gracias a este hecho, los primeros 6 meses, van a ser muy estresantes, pero muy gratificantes, porque se van a meter en la creacion de una empresa o un negocio o el desarrollo de un importante proyecto, solos o con otra gente y van a disfrutar y a tener mucho exito. Los estudiantes van a tener un gran año, en el que valoraran su trabajo. En el amor les ira fenomenal y seguiran en la misma tonica en en el año anterior. Seguiran con su pareja y estaran a partir un piñon. Vease compromiso o boda??? O si estan solos, encontraran una pareja seria y estable de la que se enamoraran. En el trabajo mucha inestabilidad y muchos cambios. Lo importante es que a pesar de la tension, viviran momentos muy glamurosos y excitantes en su empresa y se mantendran bien alli. Los aspectos mas interesante este año seran: su imagen y calidad de vida, diversion, economia, hogar, familia, viajes al extranjero, hijos, amor, relacion de pareja, vida social, religion, filosofia, estudios y trayectoria profesional. Sus logros mas importantes en 2014 estaran relacionados con: hogar, familia, hijos, creatividad, los placeres, su imagen y su cuerpo. "));
        signos.add(4, new SignoZodiaco(tipo, "Escorpio" , "El trabajo para los Escorpio sera reflotar su mundo. Reafirmarse y fortalecerse al mismo tiempo, que los cambios se producen. En Julio se sentiran muy felices con el desarrollo de su vida profesional y sus progresos. La economia tambien mejorara, especialmente hacia finales de año. Los Escorpio estan viviendo una etapa muy seria de su vida. Desde Octubre 2012 hasta Diciembre del 2014 sera asi. Estan pensando y planificando su futuro, su vida, su vejez… Y esto les entristece, porque tienen tendencia a ver lo negativo de la vida. ueden ser disciplinados, ordenados y organizados en su estricto trabajo, pero con alegria y disfrutar de las cosas. La transicion de Saturno por su signo les afecta a su salud, pero si miden sus energias y aprenden a hacer reservas de energia, no tendran problemas. Su forma seria de tomarse el trabajo, mas la presencia de Saturno en su casa del trabajo, a partir del 16 de Julio, les aportaran el exito en el campo laboral. Intelectualmente es un gran año para los estudiantes Escorpio. Van a tener un buen año de buenas notas, facilidad para organizarse y buen rollo. Jupiter se encontrara en su IX casa de la Espiritualidad, lo cual va a beneficiar a los estudiantes y a su vida laboral tambien. Buena suerte en los viajes al extranjero. Van a tener mucha suerte. Su vida social se volvera mas espiritual y les apetecera mas un seminario o ir de meditacion, que salir de marcha, gracias a Neptuno en su casa V. La presencia de Urano en su casa VI hara que tengan muchos cambios en el trabajo y en su dieta. Sus areas de interes seran: su vida profesional, el cuerpo y su imagen, los hijos, la creatividad, la diversion, los viajes al extranjero y la salud. Sus logros mas importantes en 2014 estaran relacionados con: los viajes al extranjero, la salud, la espiritualidad, la religion, la filosofia, su cuerpo, su imagen, los placeres y la diversion."));
        signos.add(5, new SignoZodiaco(tipo, "Geminis" , "El año 2014 sera un año de importantes mejoras financieras. Si estan pendientes, cada mes podran mejorar considerablemente. Hay que saber pillar el momento y planificar. En Noviembre podrian empezar de cero en el trabajo, si les interesa, con mucho exito. En Diciembre viviran un torrido mes en el amor y con el dinero. ¡Podrian recibir una gran sorpresa! Los Geminis estan viviendo un periodo de gran prosperidad desde Junio de 2012 y continuaran con la misma tendencia. Pluton sigue en su casa IX, por lo que seguiran dandole vueltas al tema de la Muerte. Es un tema que les preocupa, tanto por la Muerte o Fin de un Ciclo en si, como por la Muerte fisica que hayan vivido y experimentado con algun ser querido fallecido. En cuanto a sus estudios o su trayectoria profesional, van a vivir un cambio, ya que Neptuno deja su casa IX, para trasladarse a su casa X y ello traera cambios de apreciacion a su vida laboral y de estudios. Ya no va a ser suficiente para Vds. ganar dinero y que reconozcan su valia o aprobar examenes, sino que van a ir mas lejos. Para Vds. debera tener un sentido mas profundo y mas humano. Jupiter se instalara en su casa III y su comunicacion y sus intereses intelectuales cambiaran y mejoraran. Los Geminis se volveran mas agudos y les valoraran mas. A mediados de Julio esta previsto que hagan un gran viaje al extranjero, que les encantara. Los temas de interes del año 2014 seran: comunicacion, espiritualidad, finanzas, la diversion, los hijos, la creatividad, la salud, el sexo, la muerte, la reencarnacion, su vida profesional o los estudios, los amigos, las actividades. Sus logros mas importantes en 2014 estaran relacionados con: la economia, la creatividad, los hijos, la diversion, la comunicacion y la intelectualidad. "));
        signos.add(6, new SignoZodiaco(tipo, "Leo" , "Lo importante para los Leo en 2014 sera su realizacion personal y esto pasa por una espiritualidad acentuada en su forma de comportarse y de pensar. Quieren construirse una nueva vida en otra parte, pero deben actuar con tranquilidad. Quieren dejar atras el nerviosismo y el estres. En Agosto se volveran mas practicos; y en Diciembre encontraran la oportunidad y el progreso. Los Leo estan en una fuerte etapa espiritual desde Julio 2013. Eso significa que estan viviendo un profundo crecimiento personal y espiritual. Tambien significa que enfocan su vida de otra forma y aparecen perspectivas de cambios positivos en su vida. Jupiter entra en su signo el 16 de Julio aportando prosperidad y bienestar hasta el 2016. En cuanto al amor, sera un año importante. Empezaran despacito, pero a partir del 16 de Julio con la llegada de Jupiter, todo cambia y el amor tomara muchisima importancia. Una relacion muy seria y profunda se establecera en su vida. Urano esta en la IX casa de las creencias, religion y filosofia desde 2011. En 2014 seguimos en ella y eso les hara replantearse muchas cosas sobre estos temas y hara que cambie su percepcion sobre muchas otras cosas. La salud sera buena, pero a finales de año deberan cuidarse y descansar porque sera un año estresante igual que el anterior. Lo que ocurre es que lo llevan muy bien y saben afrontar muy bien todo lo que se les va presentando. Cuando a finales del 2014 Saturno se mueva, entonces deberan controlar bien sus energias y hacer reservas de ellas. Lo mas importante para ellos en 2014 sera: la espiritualidad, la religion, la filosofia, el esoterismo, la familia, los hijos, el hogar, el cuidado de su cuerpo y su imagen, la salud, el trabajo, el sexo, los impuestos, las deudas, las propiedades, los viajes al extranjero. Los logros mas importantes en 2014 estaran relacionados con: los placeres, el cuidado de su cuerpo y su imagen, la espiritualidad, el hogar, la familia, la comunicacion y lo intelectual. "));
        signos.add(7, new SignoZodiaco(tipo, "Libra" , "La vida social sera clave para los Libra en el año 2014. Les influira en su vida profesional y en la evolucion y el progreso de sus finanzas. Estableceran contactos laborales muy interesantes, para su trabajo al mismo tiempo que se divierten y se relacionan. La familia, el hogar, las propiedades acaparan su atencion todo el año. Su pareja sera la llave, para sobrellevar todo esto. El año 2014 estara lleno de retos para los Libra, pero despues de lo que han vivido y tenido que afrontar desde 2011, ya estan preparados para afrontarlo mental y fisicamente a la perfeccion. Es un milagro que sigan sanos y cuerdos. Les esperan cosas preciosas este año y se lo han ganado. En el trabajo les espera un ascenso y grandes recompensas de aqui hasta el 16 de Julio. Los estudiantes sacaran buenos resultados y les reconoceran el esfuerzo. Con el dinero sigue sin irles demasiado bien, al igual que el año pasado. Saturno sigue estando en su casa de la Economia y necesita reestructurar y organizar sus finanzas. Si quieren sentirse bien, cuidense porque la salud no sera muy buena. Descansen, relajense y si no se encuentran bien, vayan al medico. Lo que mas les va a interesar este año es: su profesion, sus amigos, sus actividades, la economia, el hogar, la familia, la salud, el amor, las relaciones de pareja, el cuidado de su imagen y su cuerpo y la diversion. Sus logros mas importantes en 2014 estaran relacionados con: su cuerpo y su imagen, la economia, la diversion y los placeres, los amigos y su carrera profesional. "));
        signos.add(8, new SignoZodiaco(tipo, "Piscis" , "El año 2014 va a ser un año de analisis interior para los Piscis, especialmente en verano. Este año quiere marcar la diferencia y tendra un mensaje muy importante que transmitir. Puede hacerlo, lancense. Mucho cuidado con la economia, controlen bien sus numeros. Su vida profesional recibira un buen empujon hacia finales de año. Noviembre y Diciembre. Los Piscis tendran un año 2014 mas etereo que nunca. Si ya de costumbre se encuentran a sus anchas en el mundo espiritual e invisible, este año todavia lo sera mas. Debido a Neptuno, esta tendencia sera aun mas fuerte. Deberan esforzarse en actuar sobre la tierra y ser conscientes, que su presencia en en el mundo real es fundamental para existir. En 2014 seguiran en la tendencia de los ultimos tiempos, bonanza, prosperidad y felicidad. Jupiter entro en Junio 2013 en su V casa de la Diversion y la Creatividad y seguira alli hasta Julio. Eso significa que la diversion y la felicidad ocuparan el 1º semestre de su vida. A partir de esa fecha Jupiter pasara a su casa VI del Trabajo y significa que estara mas serio y centrado en lo que tiene que hacer. Esto beneficiara a los Piscis que esten buscando trabajo. Si buscan quedarse embarazadas, 2014 sera un año de fertilidad suprema. Al igual que el año pasado, en 2014 la creatividad la tendran a flor de piel y podrian crean grandes cosas. Los estudiantes este año no lo tendran muy facil, lo que no quiere decir malo, pero si cambiante. Los cambios de cursos, de clases, de profesores, de estudios, de centro de estudios… Seran constantes. Quizas puedan ser desestabilizantes, pero no malos. En el amor continua la tendencia del año pasado, 2014 sera un año mas bien para ligues y tonteos, que para encontrar pareja. Los temas que mas les interesaran seran: religion, comunicacion, estudios superiores, salud, trabajo, amigos, atividades. viajes a extranjero, finanzas, hijos, diversion, creatividad. Sus logros mas importantes en 2014 estaran relacionados con: creatividad, hijos, salud, trabajo, viajes al extranjero, estudios superiores, ocultismo, sexo, impuestos, propiedades, dinero de otros."));
        signos.add(9, new SignoZodiaco(tipo, "Sagitario" , "Si son capaces de controlar su egocentrismo, van a encontrarse con colaboraciones que pueden resultar muy interesantes para Vds. Especialmente durante los primeros 6 meses. En Julio sentiran la necesidad de viajar o de enfocar su vida de otra forma y apareceran las oportunidades para hacerlo. En Agosto y Septiembre podrian aparecer oportunidades de desarrollo profesional. Los Sagitario son muy alegres, fiesteros y viajeros.Desde 2011 han llevado una vida social muy activa, muchas relaciones de pareja, que acabaron en boda, felicidad a tope… Esta es su naturaleza, pero este año 2014 sera especial. 2014 anuncia muchos viajes y desplazamientos y vida social fuera de lo normal. Podran hacer todo aquello que desean y seran muy felices en su vida de pareja y se sentiran bien consigo mismos. El 16 Julio Jupiter entra en el signo de Leo y los Sagitario que son todavia estudiantes, se veran muy beneficiados. Tendran mucha suerte con los examenes, sacaran muy buenas notas y su vida en general sera de felicidad. Su vida espiritual sera muy rica y experimentaran al maximo, para poder alcanzar la sabiduria. Quieren compender el secreto del mundo y de la vida. Su vida sexual sera mucho mas activa que de costumbre. Experimentaran tambien sobre ello y reinventaran el Kamasutra si les dejan… La estetica, la belleza, el culto al cuerpo… trabajaran duro para conseguir el ideal de cuerpo humano. Seguiran una dieta estricta y haran deporte, todo por conseguir el cuerpo perfecto. Tendran problemas en educar a sus hijos, les parecera dificil. El secreto es darles un poco mas de libertad. Lo que mas les interesara en 2014 seran: los viajes al extranjero, los estudios superiores, la intelectualidad, la espiritualidad, la economia, la familia, el hogar y los hijos, la creatividad, los impuestos, las propiedades, los amigos. Sus logros mas importantes en 2014 estaran relacionados con: el sexo, los viajes, las relaciones, los amigos, los estudios, la religion, la filosofia, la espiritualidad, las actividades, los impuestos, las propiedades. "));
        signos.add(10, new SignoZodiaco(tipo, "Tauro" , "En 2014 buscaran realizar sus ideales dentro de su vida cotidiana ººEl 2014 es un año muy prometedor en cuanto a encontrar la felicidad y disfrutar de la vida, especialmente en los meses de Agosto y Septiembre. Buenas noticias en lo economico en Julio. Y a partir de Diciembre mostrara mas iniciativa en el trabajo o en los estudios. ººLos pasados años han sido muy prosperos para los Tauro y se sienten muy satisfechos por ello. Pudieron crecen profesional, intelectual y espiritualmente. En 2014 seguiran con la misma tendencia, por lo que las oportunidades estaran al alcance de sus manos y dependera de ellos si las aprovechan o no. El amor, la vida social y sus relaciones laborales no fueron muy bien. Tuvieron problemas por llevarse bien con unos y con otros. ººEn 2014 seguira la misma tendencia a chocar con los demas, pero parece que han aprendido de sus errores y saben manejar mejor las situaciones. Seguiran viviendo una expansion espiritual importante, porque Urano se ha instalado en su casaa XI y ello hara que atraigan hacia Vds. mas amigos espirituales y podran debatir y desarrollar estos temas mas a fondo. ¡Muy bien los estudiantes! Con Pluton en su casa IX, durante años, tendran tendencia de filosofar, hablar de religion y desintoxicarse de una forma de pensar totalmente obsoleta, donde adoptaran formas nuevas de pensar. En 2014 habra muchos temas que les interesen, pero especialmente: la comunicacion, la familia, la salud, el amor, los ligues, la vida social, los amigos, los viajes a paises extranjeros, las actividades varias y la espiritualidad. Sus logros mas importantes en 2014 estaran relacionados con: comunicacion, vida espiritual, hogar, familia, salud y trabajo."));
        signos.add(11, new SignoZodiaco(tipo, "Virgo" , "El primera parte año 2014 sera para los Virgo un intensivo de vigilarse la salud y mirar su dia a dia al detalle. En Mayo y en Julio estaran centrados en su trabajo y tendran muy buenas iniciativas. En Agosto haran grandes progresos a pesar de las criticas, que habra contra ellos. Ganaran dinero extra en Octubre y Noviembre, con lo que tendran algunas alegrias. En 2012 y 2013 fueron años de mucho esfuerzo y mucho trabajo, del que extrajeron grandes exitos. Ahora en 2014 tambien recogeran grandes exitos. Se les presentaran buenas oportunidades, que sabran aprovechar y triunfaran. Se les reconocera su trabajo y su esfuerzo y sus proyectos seran utilizados y seguidos por todos. Para los estudiantes igual, el curso se lo sacaran con facilidad, les reconoceran su esfuerzo y sus resultados y unos de sus trabajos sera admirado por todos. Le pondran un sobresaliente. El 16 de Julio, Jupiter entra en su casa IX de la espiritualidad y vivira un periodo de crecimiento espiritual y personal. Esto le llevara a una etapa de desarrollo y exitos. Urano entra en su casa VIII de transformacion y regeneracion, por lo que les llevara a entrar en una etapa sexualmente muy activa. Su Libido sera mucho mas fuerte, que de costumbre. Le esperan experiencias interesantes y entretenidas. Su vida social y el amor les ira igual de bien que desde 2012, pero digamos que la entrada de Neptuno en su VII casa hara que se relacionen con gente de mas clase. El amor lo viviran de una forma pasional, pero tambien sera relaciones serias con vistas a un serio compromiso y boda. Saturno en su III casa le aportara problemas con sus hermanas, primas, vecinas… Se convertiran en un gran problemas para Vds. porque despertaran envidias y comprenderan que es mejor hablar lo minimo posible, para no tener roces. Lo mas interesante para Vd. este año sera: la comunicacion y la vida intelectual, espiritualidad, amor y vida de pareja, sexo, hijos, diversion, amigos, esoterismo, creatividad, deudas, impuestos, propiedades, transformacion y crecimiento espiritual. Los logros mas importantes en 2014 estaran relacionados con: la economia, la espiritualidad, los amigos, la economia, la comunicacion y lo intelectual."));
    }

    public SignoZodiaco getZodiaco(GregorianCalendar fecha) {
        int year = fecha.get(Calendar.YEAR);
        if (fecha.after(new GregorianCalendar(year-1, Calendar.DECEMBER, 21)) && fecha.before(new GregorianCalendar(year, Calendar.JANUARY, 19))) {
            return signos.get(2);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.JANUARY, 20)) && fecha.before(new GregorianCalendar(year, Calendar.FEBRUARY, 18))) {
            return signos.get(0);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.FEBRUARY, 19)) && fecha.before(new GregorianCalendar(year, Calendar.MARCH, 20))) {
            return signos.get(8);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.MARCH, 21)) && fecha.before(new GregorianCalendar(year, Calendar.APRIL, 20))) {
            return signos.get(1);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.APRIL, 21)) && fecha.before(new GregorianCalendar(year, Calendar.MAY, 20))) {
            return signos.get(10);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.MAY, 21)) && fecha.before(new GregorianCalendar(year, Calendar.JUNE, 20))) {
            return signos.get(5);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.JUNE, 21)) && fecha.before(new GregorianCalendar(year, Calendar.JULY, 20))) {
            return signos.get(3);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.JULY, 21)) && fecha.before(new GregorianCalendar(year, Calendar.AUGUST, 21))) {
            return signos.get(6);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.AUGUST, 22)) && fecha.before(new GregorianCalendar(year, Calendar.SEPTEMBER, 22))) {
            return signos.get(11);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.SEPTEMBER, 23)) && fecha.before(new GregorianCalendar(year, Calendar.OCTOBER, 22))) {
            return signos.get(7);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.OCTOBER, 23)) && fecha.before(new GregorianCalendar(year, Calendar.NOVEMBER, 22))) {
            return signos.get(4);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.NOVEMBER, 23)) && fecha.before(new GregorianCalendar(year, Calendar.DECEMBER, 20))) {
            return signos.get(9);
        }
        return signos.get(0);
    }
    
}
