/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rv.proyect1.controllers;

import java.util.GregorianCalendar;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author rafael
 */
public class ZodiacoChino implements ZodiacoInterface {
    ArrayList<SignoZodiaco> signos;

    public ZodiacoChino() {
        String tipo = "chino";
        signos = new ArrayList(12);
        signos.add(0, new SignoZodiaco(tipo, "Rata", "Los que han nacido en 1900, 1912, 1924, 1936, 1948, 1960, 1972, 1984, 1996. Este sera el año de los negocios, muy buen año laboral y economico. Puedes encontrar tu equilibrio economico, pero a cambio, sera necesario un duro trabajo, aunque merecera la pena. La rata debe pensar en el presente y dejar atras el pasado, no pensar en antiguas ilusiones para no perder las oportunidades que la vida te depara en el presente. Debe olvidar viejos rencores y tener la mente abierta para perdonar y dejar antiguos rencores, de esta manera seras mas feliz y desprenderas energia positiva. Este año tienes que tener claro cuales son sus aspiraciones en la vida e intentar alcanzarlas."));
        signos.add(1, new SignoZodiaco(tipo, "Buey", "Los que han nacido en 1901, 1913, 1925, 1937, 1949, 1961, 1973, 1985, 1997. Este año el buey tendra una evolucion laboral, tienes que esforzarte al maximo para ver resultados. Se van a resolver muchos problemas del año pasado, pero no te despreocupes del todo, todavia faltara algun asunto que tendras que resolver. En el amor debes demostrar mas tus sentimientos y ser mas romantico con tu pareja, en el amor son necesarias las demostraciones, no solo las palabras. Tienes que dejar a un lado esa timidez y lanzarte mas al amor. Si no tienes pareja no te impacientes, al final todo llega, tu pareja esta cerca y entrara en tu vida cuando dejes ansiarlo con tantas ganas."));
        signos.add(2, new SignoZodiaco(tipo, "Tigre", "Los que han nacido en 1902, 1914, 1926, 1938, 1950, 1962, 1974, 1986, 1998. Este año va a ser un año de cambios, puede ser que te mudes de casa, que te cambies de trabajo o que tengas un bebe. Estos cambios te produciran mucha tension, pero se vera compensada por la alegria que te proporcionaran. Debes controlar tu impulsividad y terquedad para triunfar este nuevo año. Trata de escuchar a tus amigos y familiares cuando te necesiten para poder ayudarlos, veras como te sientes mejor. Es un año muy importante para todos los que tienen pareja. Ha llegado el momento de alejar los miedos y enseñar tus verdaderos sentimientos, tienes que confiar en la persona que amas y saber que es la persona que mas te conviene en tu vida. Sino tienes pareja no te preocupes, vas a estar esplendido y vas a tener muchos pretendientes, quiza te sientes un poco solo por el deseo que tienes de encontrar una persona especial. No te preocupes porque la vas a conocer, hasta que ese momento llegue aprovecha al maximo tu solteria, sal y diviertete."));
        signos.add(3, new SignoZodiaco(tipo, "Gato", "Los que han nacido en 1903, 1915, 1927, 1939, 1951, 1963, 1975, 1987, 1999. Es muy buen año para el conejo, aprovecha todas las oportunidades que se te van a presentar y disfruta del año. Evita ser tan impulsivo y piensa antes de hablar, de esta manera evitaras arrepentirte de tus palabras. Va a ser un año de revelacion, viviras muchas experiencias y descubriras que es lo que quieres hacer realmente en la vida. El conejo es la representacion de la fertilidad. Eres una persona muy romantica, si no tienes pareja es un buen año para encontrarla. Tu gran atractivo y sex apeal van a atraer a personas que hasta el momento no podias imaginar, vas a tener muchas alternativas. Se selectiva y no te dejes influenciar por nadie."));
        signos.add(4, new SignoZodiaco(tipo, "Dragon", "Los que han nacido en 1904, 1916, 1928, 1940, 1952, 1964, 1976, 1988, 2000. Tendras mucha suerte este año, acabaras con exito muchos proyectos que tenias abiertos. Es un año que vas a ver realizados los sueños que creias imposibles. La pareja sera un apoyo muy importante en tu vida, no olvides todo lo que te ha ayudado y ha estado a tu lado apoyandote en todo momento. Estaras mas centrado en aspectos laborales. No descuides a tu pareja y encuentra un equilibrio entre tu relacion y los demas aspectos de tu vida. Si no tienes pareja tampoco sera una prioridad encontrarla. Preferiras el exito economico o laboral antes que ponerte a buscar a tu media naranja. Si se presenta, ¡no le dejes escapar!. Principios de año es una epoca muy buena para encontrar el amor y empezar una nueva relacion. Desprenderas mucha energia positiva y tu atractivo personal te permitira conquistar una persona especial que va a aparecer en tu vida."));
        signos.add(5, new SignoZodiaco(tipo, "Serpiente", "Los que han nacido en 1905, 1917, 1929, 1941, 1953, 1965, 1977, 1989, 2001. La serpiente debe pensar antes de hablar y evitar ser tan impulsivo. Ten mas calma e intenta relajarte, puedes cometer errores por no pensar con calma antes de expresar tu opinion, especialmente en el amor, cuenta con tu pareja a la hora de decidir. Intenta no ser tan exagerado, se prudente y guardate para ti tus victorias para evitar posibles envidias. Este año vas a aprovechar todas las oportunidades y tener exito en todo lo que realices."));
        signos.add(6, new SignoZodiaco(tipo, "Caballo", "Los que han nacido en 1906, 1918, 1930, 1942, 1954, 1966, 1978, 1990, 2002. Este es un año de aprendizaje, avanza hacia tus objetivos. Reflexiona tus errores y encuentra la mejor manera de corregirlos. Para mejorar como persona es importante que te conozcas muy bien a ti mismo. Deja de lado las amistades que no merecen la pena y centrate en personas a las que realmente les intereses. Piensa en tu futuro y en lo que quieres hacer con tu vida. No te preocupes tanto por la aprobacion de los demas y haz lo que de verdad quieras hacer, pensando solo en ti. Te centraras mas en tu relacion. Pensaras en algo mas serio que una relacion pasajera, te daras cuenta de tus verdaderos sentimientos. Si no tienes pareja este año tendras mucha suerte en el amor, con muchas oportunidades de encontrar una persona especial. La encontraras y seras correspondido, siempre que seas como tu eres. Olvidate de querer impresionar y se natural, es la mejor manera de conquistarle. "));
        signos.add(7, new SignoZodiaco(tipo, "Cabra", "Los que han nacido en 1907, 1919, 1931, 1943, 1955, 1967, 1979, 1991, 2003. Tienes que ser mas directo, no le des tantas vueltas a las cosas. Este año tendras muy buenas oportunidades, no las desaproveches. Tienes que aprender a aceptar tus defectos e intentar corregirlos. No vivas siempre pendiente de complacer al resto ni del que diran, piensa en ti y aprende a ser mas independiente. No te dejes vencer por tus miedos o inseguridades, toma tus propias decisiones basadas en tu experiencia. En el amor tendras un año muy bueno, si tienes pareja esta sera tu mayor apoyo e incluso, te plantearas el matrimonio. Tienes que dejar de lado los defectos de su pareja y fijarte en sus virtudes, que sabes que son muchas, aceptar a tu pareja por lo que es y no pongas ninguna condicion en el amor. Si no tienes pareja intenta ser mas seductor y no tan calculador."));
        signos.add(8, new SignoZodiaco(tipo, "Mono", "Los que han nacido en 1908, 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004. Tendras un buen año gracias a tu carisma y tu talento. Este año triunfaras en todos los aspectos. Eres una persona muy sociable y la gente se sentira atraida por tu caracter. Este año debes empezar a pensar en sentar la cabeza, eres el signo mas romantico y enamoradizo del horoscopo chino, tus relaciones son breves porque no te gusta tomarte en serio las relaciones. Si no tienes pareja ha llegado el momento que todo puede cambiar y debes probar una relacion para saber si es lo que realmente quieres. Te gustara la experiencia y al final acabaras cambiando. Principios de año es un mes clave si estas pensando en empezar a salir con una persona, no te cortes y expresale tus sentimientos. Acabareis adaptandoos y la relacion saldra adelante."));
        signos.add(9, new SignoZodiaco(tipo, "Gallo", "Los que han nacido en 1909, 1921, 1933, 1945, 1957, 1969, 1981, 1993. Muy buen año para los gallos, piensa lo que quieres conseguir en la vida y lo lograras. Confia en tus capacidades. Estas acostumbrado a ser el centro de atencion y a destacar del resto, siempre das lo mejor de ti y te esfuerzas al maximo, esto te ayudara a triunfar este año. No intentes abarcar todas las tareas tu solo, deja que tus compañeros o amigos te ayuden para rentabilizar los esfuerzos al maximo, de esta manera obtendras magnificos resultados, pero deberas ser paciente, no veras efectos inmediatos. Lo unico que debes evitar es el orgullo. Si tienes pareja debes aclarar si la quieres de verdad o si prefieres seguir tu camino en solitario. Si estas seguro de tus sentimientos ha llegado el momento de dar un paso mas y avanzar en la relacion. Ten cuidado con los celos, tu pareja no te da motivos para desconfiar, intenta tener la mente mas abierta."));
        signos.add(10, new SignoZodiaco(tipo, "Perro", "Los que han nacido en 1910, 1922, 1934, 1946, 1958, 1970, 1982, 1994. Es un año importante para que reflexiones, no te lamentes por errores pasados, aprende de ellos y corrigelos. Eres una persona muy fiel y trabajadora, este año buscaras mayor estabilidad para tu familia, pero no te descentres de tu trabajo. Tendras nuevos retos y oportunidades que no podras rechazar. Toma tus propias decisiones segun lo que realmente quieres y te hace feliz a ti. Analiza tu relacion, es muy importante la comunicacion. Habla con tu pareja de los problemas que teneis y juntos los podreis resolver. Vuestra relacion saldra mas reforzada. Ademas, eres uno de los signos mas fieles del horoscopo chino, la pareja que todos quisieran tener."));
        signos.add(11, new SignoZodiaco(tipo, "Jabali", "Los que han nacido en 1911, 1923, 1935, 1947, 1959, 1971, 1983, 1995. Es un año de aprendizaje, no te gustaran algunas cosas que haces y querras cambiarlas, no seas tan duro contigo mismo porque todo el mundo comete errores, lo importante es saber corregirlos y aprender de ellos. Ha llegado el momento de planificar y preocuparte mas por tu futuro, centrate en lo que realmente quieres conseguir y lanzate a por ello. Debes hacer algunos cambios si quieres triunfar, no ocultes tus sentimientos y se capaz de mostrarlos, haz lo que realmente te gusta y quieras hacer, pues de esta manera seras feliz. Es muy buen año para el amor, desprenderas mucho sex appeal, podras enamorar a la persona que te guste. Debes tener cuidado con tu orgullo, especialmente con tu pareja, intenta entenderle mas y evitar malentendidos. Hablar mucho entre vosotros, la comunicacion es fundamental."));
    }

    public SignoZodiaco getZodiaco(GregorianCalendar fecha) {
        int year = fecha.get(Calendar.YEAR);
        year = year - 1900;
        int signo = 0;
        
        while (year >= 0) {            
            if ((year % 12) == 0) {
                return signos.get(signo);
            }
            year -= 1;
            signo += 1;
        }
        
        return signos.get(11);
    }
}
