/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rv.proyect1.controllers;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author rafael
 */
public class ZodiacoGriego implements ZodiacoInterface {
    ArrayList<SignoZodiaco> signos;

    public ZodiacoGriego() {
        String tipo = "griego";
        signos = new ArrayList(12);
        signos.add(0, new SignoZodiaco(tipo, "Acuario", "Los Acuario se encontrarán en un momento en el cual su forma de actuar será poco convencional y deberán esforzarse por cambiar y llevar a término sus proyectos. Esperense a que el año 2014 sea para Vds. muy explosivo y tenso, hasta que se decidan a reafirmarse y ser consecuentes con sus actos. Pero en Julio se encontrarán con alguien, que se aliará con Vds. y será algo muy constructivo para su vida. Su trabajo va a ser duro como lo viene siendo desde Octubre 2012, pero si siguen perseverando conseguirán tener éxito a largo plazo. En Junio 2013 entraron en un círculo de prosperidad y continuarán así. Buenos trabajos, ascensos, proyectos exitosos… Los estudiantes conseguirán sacar un buen año, aunque a costa de un duro esfuerzo. Neptuno está en su casa del dinero desde Febrero del 2012 y lo seguirá estando muchos años más. Lo que significa, que el dinero les lloverá del cielo y les seguirá yendo muy bien. Tienen una intuición muy buena, para los negocios y para las inversiones. Van camino de ganar mucho dinero. A partir del 16 de Julio, Júpiter entrará en su casa VII del Amor, el matrimonio y la vida social. Vds. no tienen problemas amorosos. La felicidad sigue con Vds. por muchos años. En 2014 disfrutarán de buena salud, pero a partir del 16 de Julio dos planetas se alinearán y provocarán tensiones en este campo. Deberán cuidarse un poco. Un proyecto de una enorme envergadura aparecerá a partir del 26 de Julio. Urano estará retrógrado y es algo que Vds. querrán hacer para sí mismos y que lo van a crear. Los temas que más les van a interesar este año son: amor, relaciones de pareja, salud, finanzas, communication e intelectualidad, espiritualidad, carreras profesional. Sus logros más importantes en 2014 estarán relacionados con: espiritualidad, religión, filosofía, estudios superiores, viajes al extranjero, trabajo, amor, relaciones de pareja."));
        signos.add(1, new SignoZodiaco(tipo, "Aries", "La clave para los Aries en 2014 será cómo manejar sus relaciones tanto laborales como personales. Desea una mayor liberación y explorar nuevos terrenos… Cosa que a finales de año conseguirá de alguna forma, porque aparecerán interesantes posibilidades. Hay posibilidad de recibir una agradable sorpresa financiera en Mayo este año así que ¡¡Prepárense para una alegría inesperada Aries!!. En 2014 los Aries seguirán con la misma tendencia que llevan viviendo desde 2011, cambios, imprevistos, oportunidades… Pero lo importante es que Aries ha aprendido a sentirse bien gracias a estos cambios, liberado de todo tipo de ataduras, para perseguir sus sueños. El profundo desarrollo espiritual, que están viviendo comenzó en Febrero del 2012, cuando su casa XII de la Espiritualidad pasó al signo de Piscis. Esto produjo estos cambios y esta evolución interior, que durará todavía un año más, pero que les están situando en la posición correcta para afrontar todo en la vida. Plutón continuará en Capricornio, en su casa X, por lo que su trayectoria profesional y los estudios seguirán en la misma dirección que los últimos años. En definitiva, 2014 promete ser para Aries un año próspero y feliz, con mucha creatividad y suerte en las inversiones financieras. Buen momento para embarazarse, si lo desean. Será muy importante su imagen, el sexo, las relaciones de pareja, el hogar, los placeres, la familia. Sus logros más importantes en 2014 estarán relacionados con: el tema de la reencarnación y del ocultismo, la familia, los hijos, la diversión, el sexo, la transformación, la reencarnación, la muerte, la vida después de la muerte, el amor y las relaciones."));
        signos.add(2, new SignoZodiaco(tipo, "Capricornio ", "El año 2014 será como un renacer para los Capricornio, con muchos de Vds. buscando nuevas oportunidades y nuevos trabajos, dónde ver realizados sus objetivos laborales. Es necesario hacer mucha vida social, para poder relacionarse con gente, que le puede abrir las puertas a nuevas oportunidades. Necesita encontrar nuevos aliados. Ambiente más relajado en Diciembre. 2014, al igual que 2013 fue el año del amor para los Capricornio. El amor y la amistad están en el aire. Durante años han estado reinventándose y transformándose, para adaptarse a las nuevas tecnologías. Los amigos les han estado ayudando también, pero queda mucho trabajo por hacer. A partir del 16 de Julio todo irá mejor, incluso puede que tengan éxito. La Economía irá cogeando como siempre, pero a partir del 16 de Julio podrían ir mejor. Su vida profesional será activa, pero frenética. Podría conseguir el éxito a costa de duro trabajo y mucho esfuerzo. Lo difícil será compaginar su trabajo con sus obligaciones familiares. Neptuno estará en su casa III, la de la Comunicación, lo que significa que ha mejorado en su vida social, porque se ha esforzado en comportarse correctamente y no como le da la gana. Los estudiantes este año tendrán que hacer el esfuerzo de aprender a integrar la lógica y la intuición. Su situación familiar será inestable y cambiante y les afectará mucho. Su reto en 2014 será mantener su equilibrio emocional, muy debilitado ya. Sus áreas de mayor interés serán: el amor, la seducción, su cuerpo, su imagen sus placeres personales, la comunicación, la intelectualidad, los impuestos, las deudas, las propiedades, el ocultismo, los amigos, las actividades, el sexo, la reinvención personal. Sus logros más importantes en 2014 estarán relacionados con: el sexo, el ligar, el amor, la pareja, los amigos, las actividades grupales, la reinvención personal, las propiedades, los impuestos, el ocultismo y los estudios. "));
        signos.add(3, new SignoZodiaco(tipo, "Cáncer" , "En el año 2014 harán grandes progresos en su vida laboral o en sus estudios. Los mejores meses para encontrar oportunidades y avanzar espectacularmente serán: Marzo, Abril, Septiembre, Octubre y Diciembre. Su economía mejorará considerablemente a partir del mes de Julio. Tras una dura etapa vivida desde 2011, el 2013 fue bastante mejor y en 2014 todo será más fácil para los Cáncer. Deberán controlar un poco la salud, pero todo irá bien. Después de todo lo duro que les ha pasado, en 2014 entran en una etapa de prosperidad y es debido a que Júpiter entró en Junio 2013 en Cáncer y todo ha cambiado. Gracias a este hecho, los primeros 6 meses, van a ser muy estresantes, pero muy gratificantes, porque se van a meter en la creación de una empresa o un negocio o el desarrollo de un importante proyecto, solos o con otra gente y van a disfrutar y a tener mucho éxito. Los estudiantes van a tener un gran año, en el que valorarán su trabajo. En el amor les irá fenomenal y seguirán en la misma tónica en en el año anterior. Seguirán con su pareja y estarán a partir un piñón. Véase compromiso o boda??? O si están solos, encontrarán una pareja seria y estable de la que se enamorarán. En el trabajo mucha inestabilidad y muchos cambios. Lo importante es que a pesar de la tensión, vivirán momentos muy glamurosos y excitantes en su empresa y se mantendrán bien allí. Los aspectos más interesante este año serán: su imagen y calidad de vida, diversión, economía, hogar, familia, viajes al extranjero, hijos, amor, relación de pareja, vida social, religión, filosofía, estudios y trayectoria profesional. Sus logros más importantes en 2014 estarán relacionados con: hogar, familia, hijos, creatividad, los placeres, su imagen y su cuerpo. "));
        signos.add(4, new SignoZodiaco(tipo, "Escorpio" , "El trabajo para los Escorpio será reflotar su mundo. Reafirmarse y fortalecerse al mismo tiempo, que los cambios se producen. En Julio se sentirán muy felices con el desarrollo de su vida profesional y sus progresos. La economía también mejorará, especialmente hacia finales de año. Los Escorpio están viviendo una etapa muy seria de su vida. Desde Octubre 2012 hasta Diciembre del 2014 será así. Están pensando y planificando su futuro, su vida, su vejez… Y esto les entristece, porque tienen tendencia a ver lo negativo de la vida. ueden ser disciplinados, ordenados y organizados en su estricto trabajo, pero con alegría y disfrutar de las cosas. La transición de Saturno por su signo les afecta a su salud, pero si miden sus energías y aprenden a hacer reservas de energía, no tendrán problemas. Su forma seria de tomarse el trabajo, más la presencia de Saturno en su casa del trabajo, a partir del 16 de Julio, les aportarán el éxito en el campo laboral. Intelectualmente es un gran año para los estudiantes Escorpio. Van a tener un buen año de buenas notas, facilidad para organizarse y buen rollo. Júpiter se encontrará en su IX casa de la Espiritualidad, lo cual va a beneficiar a los estudiantes y a su vida laboral también. Buena suerte en los viajes al extranjero. Van a tener mucha suerte. Su vida social se volverá más espiritual y les apetecerá más un seminario o ir de meditación, que salir de marcha, gracias a Neptuno en su casa V. La presencia de Urano en su casa VI hará que tengan muchos cambios en el trabajo y en su dieta. Sus áreas de interés serán: su vida profesional, el cuerpo y su imagen, los hijos, la creatividad, la diversión, los viajes al extranjero y la salud. Sus logros más importantes en 2014 estarán relacionados con: los viajes al extranjero, la salud, la espiritualidad, la religión, la filosofía, su cuerpo, su imagen, los placeres y la diversión."));
        signos.add(5, new SignoZodiaco(tipo, "Géminis" , "El año 2014 será un año de importantes mejoras financieras. Si están pendientes, cada mes podrán mejorar considerablemente. Hay que saber pillar el momento y planificar. En Noviembre podrían empezar de cero en el trabajo, si les interesa, con mucho éxito. En Diciembre vivirán un tórrido mes en el amor y con el dinero. ¡Podrían recibir una gran sorpresa! Los Géminis están viviendo un periodo de gran prosperidad desde Junio de 2012 y continuarán con la misma tendencia. Plutón sigue en su casa IX, por lo que seguirán dándole vueltas al tema de la Muerte. Es un tema que les preocupa, tanto por la Muerte o Fin de un Ciclo en sí, como por la Muerte física que hayan vivido y experimentado con algún ser querido fallecido. En cuanto a sus estudios o su trayectoria profesional, van a vivir un cambio, ya que Neptuno deja su casa IX, para trasladarse a su casa X y ello traerá cambios de apreciación a su vida laboral y de estudios. Ya no va a ser suficiente para Vds. ganar dinero y que reconozcan su valía o aprobar exámenes, sino que van a ir más lejos. Para Vds. deberá tener un sentido más profundo y más humano. Júpiter se instalará en su casa III y su comunicación y sus intereses intelectuales cambiarán y mejorarán. Los Géminis se volverán más agudos y les valorarán más. A mediados de Julio está previsto que hagan un gran viaje al extranjero, que les encantará. Los temas de interés del año 2014 serán: comunicación, espiritualidad, finanzas, la diversión, los hijos, la creatividad, la salud, el sexo, la muerte, la reencarnación, su vida profesional o los estudios, los amigos, las actividades. Sus logros más importantes en 2014 estarán relacionados con: la economía, la creatividad, los hijos, la diversión, la comunicación y la intelectualidad. "));
        signos.add(6, new SignoZodiaco(tipo, "Leo" , "Lo importante para los Leo en 2014 será su realización personal y ésto pasa por una espiritualidad acentuada en su forma de comportarse y de pensar. Quieren construirse una nueva vida en otra parte, pero deben actuar con tranquilidad. Quieren dejar atrás el nerviosismo y el estrés. En Agosto se volverán más prácticos; y en Diciembre encontrarán la oportunidad y el progreso. Los Leo están en una fuerte etapa espiritual desde Julio 2013. Eso significa que están viviendo un profundo crecimiento personal y espiritual. También significa que enfocan su vida de otra forma y aparecen perspectivas de cambios positivos en su vida. Júpiter entra en su signo el 16 de Julio aportando prosperidad y bienestar hasta el 2016. En cuanto al amor, será un año importante. Empezarán despacito, pero a partir del 16 de Julio con la llegada de Júpiter, todo cambia y el amor tomará muchísima importancia. Una relación muy seria y profunda se establecerá en su vida. Urano está en la IX casa de las creencias, religión y filosofía desde 2011. En 2014 seguimos en ella y eso les hará replantearse muchas cosas sobre estos temas y hará que cambie su percepción sobre muchas otras cosas. La salud será buena, pero a finales de año deberán cuidarse y descansar porque será un año estresante igual que el anterior. Lo que ocurre es que lo llevan muy bien y saben afrontar muy bien todo lo que se les va presentando. Cuando a finales del 2014 Saturno se mueva, entonces deberán controlar bien sus energías y hacer reservas de ellas. Lo más importante para ellos en 2014 será: la espiritualidad, la religión, la filosofía, el esoterismo, la familia, los hijos, el hogar, el cuidado de su cuerpo y su imagen, la salud, el trabajo, el sexo, los impuestos, las deudas, las propiedades, los viajes al extranjero. Los logros más importantes en 2014 estarán relacionados con: los placeres, el cuidado de su cuerpo y su imagen, la espiritualidad, el hogar, la familia, la comunicación y lo intelectual. "));
        signos.add(7, new SignoZodiaco(tipo, "Libra" , "La vida social será clave para los Libra en el año 2014. Les influirá en su vida profesional y en la evolución y el progreso de sus finanzas. Establecerán contactos laborales muy interesantes, para su trabajo al mismo tiempo que se divierten y se relacionan. La familia, el hogar, las propiedades acaparan su atención todo el año. Su pareja será la llave, para sobrellevar todo esto. El año 2014 estará lleno de retos para los Libra, pero después de lo que han vivido y tenido que afrontar desde 2011, ya están preparados para afrontarlo mental y físicamente a la perfección. Es un milagro que sigan sanos y cuerdos. Les esperan cosas preciosas este año y se lo han ganado. En el trabajo les espera un ascenso y grandes recompensas de aquí hasta el 16 de Julio. Los estudiantes sacarán buenos resultados y les reconocerán el esfuerzo. Con el dinero sigue sin irles demasiado bien, al igual que el año pasado. Saturno sigue estando en su casa de la Economía y necesita reestructurar y organizar sus finanzas. Si quieren sentirse bien, cuídense porque la salud no será muy buena. Descansen, relájense y si no se encuentran bien, vayan al médico. Lo que más les va a interesar este año es: su profesión, sus amigos, sus actividades, la economía, el hogar, la familia, la salud, el amor, las relaciones de pareja, el cuidado de su imagen y su cuerpo y la diversión. Sus logros más importantes en 2014 estarán relacionados con: su cuerpo y su imagen, la economía, la diversión y los placeres, los amigos y su carrera profesional. "));
        signos.add(8, new SignoZodiaco(tipo, "Piscis" , "El año 2014 va a ser un año de análisis interior para los Piscis, especialmente en verano. Este año quiere marcar la diferencia y tendrá un mensaje muy importante que transmitir. Puede hacerlo, lancense. Mucho cuidado con la economía, controlen bien sus números. Su vida profesional recibirá un buen empujón hacia finales de año. Noviembre y Diciembre. Los Piscis tendrán un año 2014 más etéreo que nunca. Si ya de costumbre se encuentran a sus anchas en el mundo espiritual e invisible, este año todavía lo será más. Debido a Neptuno, esta tendencia será aún más fuerte. Deberán esforzarse en actuar sobre la tierra y ser conscientes, que su presencia en en el mundo real es fundamental para existir. En 2014 seguirán en la tendencia de los últimos tiempos, bonanza, prosperidad y felicidad. Júpiter entró en Junio 2013 en su V casa de la Diversión y la Creatividad y seguirá allí hasta Julio. Eso significa que la diversión y la felicidad ocuparán el 1º semestre de su vida. A partir de esa fecha Júpiter pasará a su casa VI del Trabajo y significa que estará más serio y centrado en lo que tiene que hacer. Esto beneficiará a los Piscis que estén buscando trabajo. Si buscan quedarse embarazadas, 2014 será un año de fertilidad suprema. Al igual que el año pasado, en 2014 la creatividad la tendrán a flor de piel y podrían crean grandes cosas. Los estudiantes este año no lo tendrán muy fácil, lo que no quiere decir malo, pero si cambiante. Los cambios de cursos, de clases, de profesores, de estudios, de centro de estudios… Serán constantes. Quizás puedan ser desestabilizantes, pero no malos. En el amor continúa la tendencia del año pasado, 2014 será un año más bien para ligues y tonteos, que para encontrar pareja. Los temas que más les interesarán serán: religión, comunicación, estudios superiores, salud, trabajo, amigos, atividades. viajes a extranjero, finanzas, hijos, diversión, creatividad. Sus logros más importantes en 2014 estarán relacionados con: creatividad, hijos, salud, trabajo, viajes al extranjero, estudios superiores, ocultismo, sexo, impuestos, propiedades, dinero de otros."));
        signos.add(9, new SignoZodiaco(tipo, "Sagitario" , "Si son capaces de controlar su egocentrismo, van a encontrarse con colaboraciones que pueden resultar muy interesantes para Vds. Especialmente durante los primeros 6 meses. En Julio sentirán la necesidad de viajar o de enfocar su vida de otra forma y aparecerán las oportunidades para hacerlo. En Agosto y Septiembre podrían aparecer oportunidades de desarrollo profesional. Los Sagitario son muy alegres, fiesteros y viajeros.Desde 2011 han llevado una vida social muy activa, muchas relaciones de pareja, que acabaron en boda, felicidad a tope… Esta es su naturaleza, pero este año 2014 será especial. 2014 anuncia muchos viajes y desplazamientos y vida social fuera de lo normal. Podrán hacer todo aquello que desean y serán muy felices en su vida de pareja y se sentirán bien consigo mismos. El 16 Julio Júpiter entra en el signo de Leo y los Sagitario que son todavía estudiantes, se verán muy beneficiados. Tendrán mucha suerte con los exámenes, sacarán muy buenas notas y su vida en general será de felicidad. Su vida espiritual será muy rica y experimentarán al máximo, para poder alcanzar la sabiduría. Quieren compender el secreto del mundo y de la vida. Su vida sexual será mucho más activa que de costumbre. Experimentarán también sobre ello y reinventarán el Kamasutra si les dejan… La estética, la belleza, el culto al cuerpo… trabajarán duro para conseguir el ideal de cuerpo humano. Seguirán una dieta estricta y harán deporte, todo por conseguir el cuerpo perfecto. Tendrán problemas en educar a sus hijos, les parecerá difícil. El secreto es darles un poco más de libertad. Lo que más les interesará en 2014 serán: los viajes al extranjero, los estudios superiores, la intelectualidad, la espiritualidad, la economía, la familia, el hogar y los hijos, la creatividad, los impuestos, las propiedades, los amigos. Sus logros más importantes en 2014 estarán relacionados con: el sexo, los viajes, las relaciones, los amigos, los estudios, la religión, la filosofía, la espiritualidad, las actividades, los impuestos, las propiedades. "));
        signos.add(10, new SignoZodiaco(tipo, "Tauro" , "En 2014 buscarán realizar sus ideales dentro de su vida cotidiana ººEl 2014 es un año muy prometedor en cuanto a encontrar la felicidad y disfrutar de la vida, especialmente en los meses de Agosto y Septiembre. Buenas noticias en lo económico en Julio. Y a partir de Diciembre mostrará más iniciativa en el trabajo o en los estudios. ººLos pasados años han sido muy prósperos para los Tauro y se sienten muy satisfechos por ello. Pudieron crecen profesional, intelectual y espiritualmente. En 2014 seguirán con la misma tendencia, por lo que las oportunidades estarán al alcance de sus manos y dependerá de ellos si las aprovechan o no. El amor, la vida social y sus relaciones laborales no fueron muy bien. Tuvieron problemas por llevarse bien con unos y con otros. ººEn 2014 seguirá la misma tendencia a chocar con los demás, pero parece que han aprendido de sus errores y saben manejar mejor las situaciones. Seguirán viviendo una expansión espiritual importante, porque Urano se ha instalado en su casaa XI y ello hará que atraigan hacia Vds. más amigos espirituales y podrán debatir y desarrollar estos temas más a fondo. ¡Muy bien los estudiantes! Con Plutón en su casa IX, durante años, tendrán tendencia de filosofar, hablar de religión y desintoxicarse de una forma de pensar totalmente obsoleta, dónde adoptarán formas nuevas de pensar. En 2014 habrá muchos temas que les interesen, pero especialmente: la comunicación, la familia, la salud, el amor, los ligues, la vida social, los amigos, los viajes a países extranjeros, las actividades varias y la espiritualidad. Sus logros más importantes en 2014 estarán relacionados con: comunicación, vida espiritual, hogar, familia, salud y trabajo."));
        signos.add(11, new SignoZodiaco(tipo, "Virgo" , "El primera parte año 2014 será para los Virgo un intensivo de vigilarse la salud y mirar su día a día al detalle. En Mayo y en Julio estarán centrados en su trabajo y tendrán muy buenas iniciativas. En Agosto harán grandes progresos a pesar de las críticas, que habrá contra ellos. Ganarán dinero extra en Octubre y Noviembre, con lo que tendrán algunas alegrías. En 2012 y 2013 fueron años de mucho esfuerzo y mucho trabajo, del que extrajeron grandes éxitos. Ahora en 2014 también recogerán grandes éxitos. Se les presentarán buenas oportunidades, que sabrán aprovechar y triunfarán. Se les reconocerá su trabajo y su esfuerzo y sus proyectos serán utilizados y seguidos por todos. Para los estudiantes igual, el curso se lo sacarán con facilidad, les reconocerán su esfuerzo y sus resultados y unos de sus trabajos será admirado por todos. Le pondrán un sobresaliente. El 16 de Julio, Júpiter entra en su casa IX de la espiritualidad y vivirá un periodo de crecimiento espiritual y personal. Esto le llevará a una etapa de desarrollo y éxitos. Urano entra en su casa VIII de transformación y regeneración, por lo que les llevará a entrar en una etapa sexualmente muy activa. Su Libido será mucho más fuerte, que de costumbre. Le esperan experiencias interesantes y entretenidas. Su vida social y el amor les irá igual de bien que desde 2012, pero digamos que la entrada de Neptuno en su VII casa hará que se relacionen con gente de más clase. El amor lo vivirán de una forma pasional, pero también será relaciones serias con vistas a un serio compromiso y boda. Saturno en su III casa le aportará problemas con sus hermanas, primas, vecinas… Se convertirán en un gran problemas para Vds. porque despertarán envidias y comprenderán que es mejor hablar lo mínimo posible, para no tener roces. Lo más interesante para Vd. este año será: la comunicación y la vida intelectual, espiritualidad, amor y vida de pareja, sexo, hijos, diversión, amigos, esoterismo, creatividad, deudas, impuestos, propiedades, transformación y crecimiento espiritual. Los logros más importantes en 2014 estarán relacionados con: la economía, la espiritualidad, los amigos, la economía, la comunicación y lo intelectual."));
    }

    public SignoZodiaco getZodiaco(GregorianCalendar fecha) {
        int year = fecha.get(Calendar.YEAR);
        if (fecha.after(new GregorianCalendar(year-1, Calendar.DECEMBER, 21)) && fecha.before(new GregorianCalendar(year, Calendar.JANUARY, 19))) {
            return signos.get(2);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.JANUARY, 20)) && fecha.before(new GregorianCalendar(year, Calendar.FEBRUARY, 18))) {
            return signos.get(0);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.FEBRUARY, 19)) && fecha.before(new GregorianCalendar(year, Calendar.MARCH, 20))) {
            return signos.get(8);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.MARCH, 21)) && fecha.before(new GregorianCalendar(year, Calendar.APRIL, 20))) {
            return signos.get(1);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.APRIL, 21)) && fecha.before(new GregorianCalendar(year, Calendar.MAY, 20))) {
            return signos.get(10);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.MAY, 21)) && fecha.before(new GregorianCalendar(year, Calendar.JUNE, 20))) {
            return signos.get(5);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.JUNE, 21)) && fecha.before(new GregorianCalendar(year, Calendar.JULY, 20))) {
            return signos.get(3);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.JULY, 21)) && fecha.before(new GregorianCalendar(year, Calendar.AUGUST, 21))) {
            return signos.get(6);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.AUGUST, 22)) && fecha.before(new GregorianCalendar(year, Calendar.SEPTEMBER, 22))) {
            return signos.get(11);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.SEPTEMBER, 23)) && fecha.before(new GregorianCalendar(year, Calendar.OCTOBER, 22))) {
            return signos.get(7);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.OCTOBER, 23)) && fecha.before(new GregorianCalendar(year, Calendar.NOVEMBER, 22))) {
            return signos.get(4);
        }
        else if (fecha.after(new GregorianCalendar(year, Calendar.NOVEMBER, 23)) && fecha.before(new GregorianCalendar(year, Calendar.DECEMBER, 20))) {
            return signos.get(9);
        }
        return signos.get(0);
    }
    
}
