/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rv.proyect1.controllers;

import java.util.GregorianCalendar;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author rafael
 */
public class ZodiacoChino implements ZodiacoInterface {
    ArrayList<SignoZodiaco> signos;

    public ZodiacoChino() {
        String tipo = "chino";
        signos = new ArrayList(12);
        signos.add(0, new SignoZodiaco(tipo, "Rata", "Los que han nacido en 1900, 1912, 1924, 1936, 1948, 1960, 1972, 1984, 1996. Este será el año de los negocios, muy buen año laboral y económico. Puedes encontrar tu equilibrio económico, pero a cambio, será necesario un duro trabajo, aunque merecerá la pena. La rata debe pensar en el presente y dejar atrás el pasado, no pensar en antiguas ilusiones para no perder las oportunidades que la vida te depara en el presente. Debe olvidar viejos rencores y tener la mente abierta para perdonar y dejar antiguos rencores, de esta manera serás más feliz y desprenderás energía positiva. Este año tienes que tener claro cuales son sus aspiraciones en la vida e intentar alcanzarlas."));
        signos.add(1, new SignoZodiaco(tipo, "Buey", "Los que han nacido en 1901, 1913, 1925, 1937, 1949, 1961, 1973, 1985, 1997. Este año el buey tendrá una evolución laboral, tienes que esforzarte al máximo para ver resultados. Se van a resolver muchos problemas del año pasado, pero no te despreocupes del todo, todavía faltará algún asunto que tendrás que resolver. En el amor debes demostrar más tus sentimientos y ser mas romántico con tu pareja, en el amor son necesarias las demostraciones, no solo las palabras. Tienes que dejar a un lado esa timidez y lanzarte más al amor. Si no tienes pareja no te impacientes, al final todo llega, tu pareja está cerca y entrará en tu vida cuando dejes ansiarlo con tantas ganas."));
        signos.add(2, new SignoZodiaco(tipo, "Tigre", "Los que han nacido en 1902, 1914, 1926, 1938, 1950, 1962, 1974, 1986, 1998. Este año va a ser un año de cambios, puede ser que te mudes de casa, que te cambies de trabajo o que tengas un bebe. Estos cambios te producirán mucha tensión, pero se verá compensada por la alegría que te proporcionarán. Debes controlar tu impulsividad y terquedad para triunfar este nuevo año. Trata de escuchar a tus amigos y familiares cuando te necesiten para poder ayudarlos, verás como te sientes mejor. Es un año muy importante para todos los que tienen pareja. Ha llegado el momento de alejar los miedos y enseñar tus verdaderos sentimientos, tienes que confiar en la persona que amas y saber que es la persona que mas te conviene en tu vida. Sino tienes pareja no te preocupes, vas a estar espléndido y vas a tener muchos pretendientes, quizá te sientes un poco solo por el deseo que tienes de encontrar una persona especial. No te preocupes porque la vas a conocer, hasta que ese momento llegue aprovecha al máximo tu soltería, sal y diviértete."));
        signos.add(3, new SignoZodiaco(tipo, "Gato", "Los que han nacido en 1903, 1915, 1927, 1939, 1951, 1963, 1975, 1987, 1999. Es muy buen año para el conejo, aprovecha todas las oportunidades que se te van a presentar y disfruta del año. Evita ser tan impulsivo y piensa antes de hablar, de esta manera evitarás arrepentirte de tus palabras. Va a ser un año de revelación, vivirás muchas experiencias y descubrirás que es lo que quieres hacer realmente en la vida. El conejo es la representación de la fertilidad. Eres una persona muy romántica, si no tienes pareja es un buen año para encontrarla. Tu gran atractivo y sex apeal van a atraer a personas que hasta el momento no podías imaginar, vas a tener muchas alternativas. Se selectiva y no te dejes influenciar por nadie."));
        signos.add(4, new SignoZodiaco(tipo, "Dragón", "Los que han nacido en 1904, 1916, 1928, 1940, 1952, 1964, 1976, 1988, 2000. Tendrás mucha suerte este año, acabarás con éxito muchos proyectos que tenías abiertos. Es un año que vas a ver realizados los sueños que creías imposibles. La pareja será un apoyo muy importante en tu vida, no olvides todo lo que te ha ayudado y ha estado a tu lado apoyándote en todo momento. Estarás más centrado en aspectos laborales. No descuides a tu pareja y encuentra un equilibrio entre tu relación y los demás aspectos de tu vida. Si no tienes pareja tampoco será una prioridad encontrarla. Preferirás el éxito económico o laboral antes que ponerte a buscar a tu media naranja. Si se presenta, ¡no le dejes escapar!. Principios de año es una época muy buena para encontrar el amor y empezar una nueva relación. Desprenderás mucha energía positiva y tu atractivo personal te permitirá conquistar una persona especial que va a aparecer en tu vida."));
        signos.add(5, new SignoZodiaco(tipo, "Serpiente", "Los que han nacido en 1905, 1917, 1929, 1941, 1953, 1965, 1977, 1989, 2001. La serpiente debe pensar antes de hablar y evitar ser tan impulsivo. Ten más calma e intenta relajarte, puedes cometer errores por no pensar con calma antes de expresar tu opinión, especialmente en el amor, cuenta con tu pareja a la hora de decidir. Intenta no ser tan exagerado, se prudente y guárdate para ti tus victorias para evitar posibles envidias. Este año vas a aprovechar todas las oportunidades y tener éxito en todo lo que realices."));
        signos.add(6, new SignoZodiaco(tipo, "Caballo", "Los que han nacido en 1906, 1918, 1930, 1942, 1954, 1966, 1978, 1990, 2002. Este es un año de aprendizaje, avanza hacia tus objetivos. Reflexiona tus errores y encuentra la mejor manera de corregirlos. Para mejorar como persona es importante que te conozcas muy bien a ti mismo. Deja de lado las amistades que no merecen la pena y céntrate en personas a las que realmente les intereses. Piensa en tu futuro y en lo que quieres hacer con tu vida. No te preocupes tanto por la aprobación de los demás y haz lo que de verdad quieras hacer, pensando solo en ti. Te centrarás más en tu relación. Pensarás en algo mas serio que una relación pasajera, te darás cuenta de tus verdaderos sentimientos. Si no tienes pareja este año tendrás mucha suerte en el amor, con muchas oportunidades de encontrar una persona especial. La encontrarás y serás correspondido, siempre que seas como tú eres. Olvídate de querer impresionar y sé natural, es la mejor manera de conquistarle. "));
        signos.add(7, new SignoZodiaco(tipo, "Cabra", "Los que han nacido en 1907, 1919, 1931, 1943, 1955, 1967, 1979, 1991, 2003. Tienes que ser más directo, no le des tantas vueltas a las cosas. Este año tendrás muy buenas oportunidades, no las desaproveches. Tienes que aprender a aceptar tus defectos e intentar corregirlos. No vivas siempre pendiente de complacer al resto ni del que dirán, piensa en ti y aprende a ser más independiente. No te dejes vencer por tus miedos o inseguridades, toma tus propias decisiones basadas en tu experiencia. En el amor tendrás un año muy bueno, si tienes pareja ésta será tu mayor apoyo e incluso, te plantearás el matrimonio. Tienes que dejar de lado los defectos de su pareja y fijarte en sus virtudes, que sabes que son muchas, aceptar a tu pareja por lo que es y no pongas ninguna condición en el amor. Si no tienes pareja intenta ser más seductor y no tan calculador."));
        signos.add(8, new SignoZodiaco(tipo, "Mono", "Los que han nacido en 1908, 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004. Tendrás un buen año gracias a tu carisma y tu talento. Este año triunfarás en todos los aspectos. Eres una persona muy sociable y la gente se sentirá atraída por tu carácter. Este año debes empezar a pensar en sentar la cabeza, eres el signo más romántico y enamoradizo del horóscopo chino, tus relaciones son breves porque no te gusta tomarte en serio las relaciones. Si no tienes pareja ha llegado el momento que todo puede cambiar y debes probar una relación para saber si es lo que realmente quieres. Te gustará la experiencia y al final acabarás cambiando. Principios de año es un mes clave si estás pensando en empezar a salir con una persona, no te cortes y exprésale tus sentimientos. Acabaréis adaptándoos y la relación saldrá adelante."));
        signos.add(9, new SignoZodiaco(tipo, "Gallo", "Los que han nacido en 1909, 1921, 1933, 1945, 1957, 1969, 1981, 1993. Muy buen año para los gallos, piensa lo que quieres conseguir en la vida y lo lograrás. Confía en tus capacidades. Estás acostumbrado a ser el centro de atención y a destacar del resto, siempre das lo mejor de ti y te esfuerzas al máximo, esto te ayudará a triunfar este año. No intentes abarcar todas las tareas tu solo, deja que tus compañeros o amigos te ayuden para rentabilizar los esfuerzos al máximo, de esta manera obtendrás magníficos resultados, pero deberás ser paciente, no verás efectos inmediatos. Lo único que debes evitar es el orgullo. Si tienes pareja debes aclarar si la quieres de verdad o si prefieres seguir tu camino en solitario. Si estás seguro de tus sentimientos ha llegado el momento de dar un paso más y avanzar en la relación. Ten cuidado con los celos, tu pareja no te da motivos para desconfiar, intenta tener la mente mas abierta."));
        signos.add(10, new SignoZodiaco(tipo, "Perro", "Los que han nacido en 1910, 1922, 1934, 1946, 1958, 1970, 1982, 1994. Es un año importante para que reflexiones, no te lamentes por errores pasados, aprende de ellos y corrígelos. Eres una persona muy fiel y trabajadora, este año buscarás mayor estabilidad para tu familia, pero no te descentres de tu trabajo. Tendrás nuevos retos y oportunidades que no podrás rechazar. Toma tus propias decisiones según lo que realmente quieres y te hace feliz a ti. Analiza tu relación, es muy importante la comunicación. Habla con tu pareja de los problemas que tenéis y juntos los podréis resolver. Vuestra relación saldrá mas reforzada. Además, eres uno de los signos más fieles del horóscopo chino, la pareja que todos quisieran tener."));
        signos.add(11, new SignoZodiaco(tipo, "Jabalí", "Los que han nacido en 1911, 1923, 1935, 1947, 1959, 1971, 1983, 1995. Es un año de aprendizaje, no te gustarán algunas cosas que haces y querrás cambiarlas, no seas tan duro contigo mismo porque todo el mundo comete errores, lo importante es saber corregirlos y aprender de ellos. Ha llegado el momento de planificar y preocuparte mas por tu futuro, céntrate en lo que realmente quieres conseguir y lánzate a por ello. Debes hacer algunos cambios si quieres triunfar, no ocultes tus sentimientos y se capaz de mostrarlos, haz lo que realmente te gusta y quieras hacer, pues de esta manera serás feliz. Es muy buen año para el amor, desprenderás mucho sex appeal, podrás enamorar a la persona que te guste. Debes tener cuidado con tu orgullo, especialmente con tu pareja, intenta entenderle mas y evitar malentendidos. Hablar mucho entre vosotros, la comunicación es fundamental."));
    }

    public SignoZodiaco getZodiaco(GregorianCalendar fecha) {
        int year = fecha.get(Calendar.YEAR);
        year = year - 1900;
        int signo = 0;
        
        while (year >= 0) {            
            if ((year % 12) == 0) {
                return signos.get(signo);
            }
            year -= 1;
            signo += 1;
        }
        
        return signos.get(11);
    }
}
